/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import View.CadastroPaciente;
import View.CadastroMedico;
import View.Agendamento;
/**
 *
 * @author Alexm
 */
public class TelaPrincipal extends javax.swing.JFrame {

     private CadastroMedico objetocadm;
     private CadastroPaciente objetocadp;
     
     private Agendamento objetoage;
        
    public TelaPrincipal() {
        initComponents();
      this.objetocadm = new CadastroMedico();
      this.objetocadp = new CadastroPaciente();
     
      this.objetoage = new Agendamento();

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b_cpaciente = new javax.swing.JButton();
        b_cmedicos = new javax.swing.JButton();
        b_agendamentos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        b_cpaciente.setText("Pacientes");
        b_cpaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cpacienteActionPerformed(evt);
            }
        });

        b_cmedicos.setText("Médicos");
        b_cmedicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cmedicosActionPerformed(evt);
            }
        });

        b_agendamentos.setText("Agendamentos");
        b_agendamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_agendamentosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Clinica Médica Bonzina");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_agendamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cmedicos, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(b_cpaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(45, 45, 45)
                            .addComponent(jLabel1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(59, 59, 59)
                .addComponent(b_cpaciente)
                .addGap(18, 18, 18)
                .addComponent(b_cmedicos)
                .addGap(18, 18, 18)
                .addComponent(b_agendamentos)
                .addGap(133, 133, 133))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cpacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cpacienteActionPerformed
      objetocadp.setVisible(true);
    }//GEN-LAST:event_b_cpacienteActionPerformed

    private void b_cmedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cmedicosActionPerformed
        objetocadm.setVisible(true);
    }//GEN-LAST:event_b_cmedicosActionPerformed

    private void b_agendamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_agendamentosActionPerformed
      objetoage.setVisible(true);
    }//GEN-LAST:event_b_agendamentosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_agendamentos;
    private javax.swing.JButton b_cmedicos;
    private javax.swing.JButton b_cpaciente;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
